export const HIRING_SIGNAL_TYPES = {
  MULTIPLE_ENGINEERING_OPENINGS: 'MULTIPLE_ENGINEERING_OPENINGS',
  RECENT_ENGINEERING_HIRING: 'RECENT_ENGINEERING_HIRING',
  RELEVANT_TECHNOLOGY_CLUSTER: 'RELEVANT_TECHNOLOGY_CLUSTER',
  CROSS_FUNCTION_ENGINEERING_HIRING: 'CROSS_FUNCTION_ENGINEERING_HIRING',
  ENGINEERING_LEADERSHIP_HIRING: 'ENGINEERING_LEADERSHIP_HIRING',
} as const;

export const RECENT_HIRING_WINDOW_MS = 1000 * 60 * 60 * 24 * 30;

export const MULTIPLE_OPENINGS_THRESHOLD = 3;
export const RECENT_OPENINGS_THRESHOLD = 3;
export const RELEVANT_TECH_JOB_THRESHOLD = 2;
